server:
  port: 8070
spring:
  application:
    name: mircoservice-router-zuul
eureka:
  client:
    service-url:
      defaultZone: http://zhangSan:zhangSan2018@localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
zuul:
  routes:
    producer-service:
      path: /user/**
      serviceId: microservice-producer-user
    consumer-service:
      path: /movie/**
      serviceId: mircoservice-consumer-movie-ribbon
ribbon:
  eureka:
    enabled: true