server:
  port: 8078
  tomcat:
    threads:
      max: 50
spring:
  application:
    name: mircoservice-invoke-feign
eureka:
  client:
    service-url:
      defaultZone: http://zhangSan:zhangSan2018@localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
feign:
  client:
    config:
      default:
        connectTimeout: 4000
        readTimeout: 4000
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
