server:
  port: 8078
spring:
  application:
    name: mircoservice-invoke-feign
eureka:
  client:
    service-url:
      defaultZone: http://zhangSan:zhangSan2018@localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}